export const GET_CURRENCY_UNIT_START = 'GET_CURRENCY_UNIT_START'
export const GET_CURRENCY_UNIT_SUCCESS = 'GET_CURRENCY_UNIT_SUCCESS'
export const GET_CURRENCY_UNIT_FAILED = 'GET_CURRENCY_UNIT_FAILED'