export const GET_CURRENCY_UNIT_START = 'GET_CURRENCY_UNIT_START'
export const GET_CURRENCY_UNIT_SUCCESS = 'GET_CURRENCY_UNIT_SUCCESS'
export const GET_CURRENCY_UNIT_FAILED = 'GET_CURRENCY_UNIT_FAILED'

export const GET_MARKET_LIST_START = 'GET_MARKET_LIST_START'
export const GET_MARKET_LIST_SUCCESS = 'GET_MARKET_LIST_SUCCESS'
export const GET_MARKET_LIST_FAILED = 'GET_MARKET_LIST_FAILED'